// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import JoinRoomController from "./join_room_controller"
application.register("join-room", JoinRoomController)

import Dialog from '@stimulus-components/dialog'
application.register('dialog', Dialog)